### ISSUE TITLE
Launch bios.lua doesn't return CraftOS Shell

### ISSUE THREAD

**Issue by cmdpwnd** [jaredallard/swarmc#6]
Attempting to get CraftOS Shell.

Launches (fork) CrfOS 1.7.4 but then returns to prompt and does not return the shell.

[http://s22.postimg.org/l05euyvf5/Untitled.png](url)

**Comment by jaredallard** [comment]
Hi! The shell is no longer run, nor shipped in it. However if you obtain
programs/shell and specify it when running swarmc it should run it. I
removed shell on start as it will run scripts specified in command line
later on.

On Thu, Apr 14, 2016, 16:52 cmdpwnd <notifications@github.com> wrote:

> Attempting to get CraftOS Shell.
>
> Launches (fork) CrfOS 1.7.4 but then returns to prompt and does not return
> the shell.
>
> http://s22.postimg.org/l05euyvf5/Untitled.png <http://url>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jaredallard/swarmc/issues/6>
>
-- 
Jared Allard, *full stack engineer*
206-375-9640 | jaredallard@outlook.com | https://jaredallard.me

**Comment by jaredallard** [comment]
Also specifying sandbox/bios.lua is redundant and just runs the bios!
